## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dsr', ['core', 'network', 'internet', 'applications', 
    'mobility', 'config-store', 'wifi', 'dsr', 'point-to-point'])
    obj.source = 'dsr.cc'
    obj = bld.create_ns3_program('my-simple-point-to-point-olsr',
                                 ['point-to-point', 'internet', 'dsr', 'applications', 'wifi'])
    obj.source = 'my-simple-point-to-point-olsr.cc'

